FROM node:20-bookworm-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends ghostscript ca-certificates \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json package-lock.json* ./
COPY prisma ./prisma

RUN npm ci

COPY . .

# Provide placeholder NEXT_PUBLIC_ vars so Next.js can inline them at build time.
# Real values are injected at runtime via Render env vars.
ARG NEXT_PUBLIC_FIREBASE_API_KEY="placeholder"
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="placeholder"
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID="placeholder"
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="placeholder"
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="placeholder"
ARG NEXT_PUBLIC_FIREBASE_APP_ID="placeholder"
ARG NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="placeholder"

ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=$NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME

RUN npm run build

ENV NODE_ENV=production
ENV PORT=10000
ENV NEXT_TELEMETRY_DISABLED=1
ENV GS_BINARY=/usr/bin/gs

EXPOSE 10000

CMD ["sh", "-c", "npx prisma migrate deploy && npm start"]
